version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: 
            - .env
        container_name: jenkins-web
        ports:
            - "8080:8080"
        volumes:
            - ./volumes:/srv/app
        restart: always