version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: 
            - .env
        container_name: jenkins-web
        ports:
            - "8080:8080"
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
            -  /var/run/docker.sock:/var/run/docker.sock
        restart: always
volumes:
    jenkins-data:
    jenkins-docker-certs: